[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
jupiter_poc = "DA8tQZHYfoPoHGusDGj9SRdzaDEuwDbUSjndCX3SzzEr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/ace.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/jupiter-swap.ts"